- hosts: all
  become: yes

  tasks:
    - name: install packages
      yum:
        name: unzip
        state: latest

    - name: Download vault binary
      get_url:
        url: https://releases.hashicorp.com/vault/1.5.5/vault_1.5.5_linux_amd64.zip
        dest: /tmp/vault.zip
        force: no

    - name: unarchive the vault zip file
      unarchive:
        src: /tmp/vault.zip
        dest: /usr/local/bin/
        remote_src: True

    - name: generate ssh-key
      openssh_keypair:
        path: "~/.ssh/id_rsa"
        type: rsa
        state: present

    - name: make vault public key 
      shell: '/usr/local/bin/vault write -field=signed_key ssh-client-signer/sign/ssh-srv-role public_key=@$HOME/.ssh/id_rsa.pub > ~/.ssh/signed.pub'
      environment:
        VAULT_ADDR: "http://192.168.1.100:8200"
        VAULT_TOKEN: "main-token"

